name: Build_and_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.3

      - name: Build
        run: go build -v

      - name: Test
        run: |
          go test -v ./data_common/...
          go test -v ./key_management/...
          go test -v ./encryption/...
          go test -v ./signature/...
          go test -v .
